import type { CategorySeed } from '../types.js';

export const ANIMAL: CategorySeed = {
  category: 'animal',
  words: [
    { word: '강아지', hint: '인간의 가장 친한 친구', difficulty: 1 },
    { word: '고양이', hint: '"야옹" 우는 반려동물', difficulty: 1 },
    { word: '호랑이', hint: '한국 민화의 산 신령', difficulty: 1 },
    { word: '사자', hint: '아프리카 초원의 왕', difficulty: 1 },
    { word: '코끼리', hint: '긴 코를 가진 큰 동물', difficulty: 1 },
    { word: '기린', hint: '목이 가장 긴 포유류', difficulty: 1 },
    { word: '하마', hint: '강에 사는 큰 회색 동물', difficulty: 1 },
    { word: '코뿔소', hint: '뿔이 코에 달린 동물', difficulty: 2 },
    { word: '원숭이', hint: '바나나를 좋아하는 동물', difficulty: 1 },
    { word: '판다', hint: '대나무 먹는 흑백 곰', difficulty: 1 },
    { word: '북극곰', hint: '얼음 위에 사는 흰 곰', difficulty: 1 },
    { word: '펭귄', hint: '날지 못하는 새, 남극', difficulty: 1 },
    { word: '독수리', hint: '하늘의 제왕', difficulty: 1 },
    { word: '참새', hint: '도시에서 흔한 작은 새', difficulty: 1 },
    { word: '비둘기', hint: '평화의 상징', difficulty: 1 },
    { word: '병아리', hint: '닭의 새끼', difficulty: 1 },
    { word: '오리', hint: '꽥꽥 우는 물새', difficulty: 1 },
    { word: '돼지', hint: '꿀꿀거리는 분홍 동물', difficulty: 1 },
    { word: '송아지', hint: '소의 새끼', difficulty: 1 },
    { word: '망아지', hint: '말의 새끼', difficulty: 1 },
    { word: '얼룩말', hint: '검은 줄무늬 초원 동물', difficulty: 1 },
    { word: '염소', hint: '"매" 우는 뿔 달린 가축', difficulty: 1 },
    { word: '토끼', hint: '귀가 길고 깡총거린다', difficulty: 1 },
    { word: '다람쥐', hint: '도토리를 모으는 작은 동물', difficulty: 1 },
    { word: '사슴', hint: '큰 뿔을 가진 숲 동물', difficulty: 1 },
    { word: '늑대', hint: '달을 보고 우는 야생 개과', difficulty: 1 },
    { word: '여우', hint: '꾀가 많기로 유명한 동물', difficulty: 1 },
    { word: '곰돌이', hint: '귀여운 곰 캐릭터/별명', difficulty: 1, alternates: ['곰'] },
    { word: '거북이', hint: '느리지만 오래 사는 동물', difficulty: 1 },
    { word: '악어', hint: '강에 사는 큰 파충류', difficulty: 1 },
    { word: '독사', hint: '독을 가진 뱀', difficulty: 1, alternates: ['뱀'] },
    { word: '고래', hint: '바다에 사는 가장 큰 포유류', difficulty: 1 },
    { word: '돌고래', hint: '영리한 바다 포유류', difficulty: 1 },
    { word: '상어', hint: '날카로운 이빨의 바다 포식자', difficulty: 1 },
    { word: '문어', hint: '다리가 여덟 개인 바다 생물', difficulty: 1 },
    { word: '오징어', hint: '먹물을 뿜는 바다 생물', difficulty: 1 },
    { word: '나비', hint: '꽃 사이를 날아다닌다', difficulty: 1 },
    { word: '잠자리', hint: '얇은 날개의 곤충, 가을', difficulty: 1 },
    { word: '꿀벌', hint: '꿀을 만드는 곤충', difficulty: 1 },
  ],
};
