import type { CategorySeed } from '../types.js';

export const FOOD: CategorySeed = {
  category: 'food',
  words: [
    { word: '김치찌개', hint: '한국 대표 국물 요리, 빨간 국물', difficulty: 1 },
    { word: '된장찌개', hint: '구수한 콩 발효 국물', difficulty: 1 },
    { word: '비빔밥', hint: '여러 재료를 한 그릇에 비빈다', difficulty: 1 },
    { word: '치킨', hint: '맥주의 단짝', difficulty: 1 },
    { word: '떡볶이', hint: '빨간 양념의 분식', difficulty: 1 },
    { word: '김밥', hint: '소풍 갈 때 자주 싸는 음식', difficulty: 1 },
    { word: '라면', hint: '봉지에 들어 있는 면 요리', difficulty: 1 },
    { word: '짜장면', hint: '검은 소스 중국집 면', difficulty: 1, alternates: ['자장면'] },
    { word: '짬뽕', hint: '빨간 국물 해물면', difficulty: 1 },
    { word: '탕수육', hint: '바삭한 튀김에 새콤달콤 소스', difficulty: 1 },
    { word: '삼겹살', hint: '한국인이 사랑하는 돼지고기 부위', difficulty: 1 },
    { word: '갈비탕', hint: '맑은 국물 소갈비 요리', difficulty: 2 },
    { word: '냉면', hint: '여름에 시원하게 먹는 면', difficulty: 1 },
    { word: '국밥', hint: '뜨끈한 국에 밥을 만 음식', difficulty: 1 },
    { word: '순대', hint: '돼지 부속과 당면을 채워 찐 음식', difficulty: 1 },
    { word: '어묵', hint: '겨울 길거리에서 국물과 함께', difficulty: 1 },
    { word: '햄버거', hint: '패스트푸드 대표주자', difficulty: 1 },
    { word: '피자', hint: '치즈가 늘어나는 이탈리아 음식', difficulty: 1 },
    { word: '파스타', hint: '서양식 면 요리', difficulty: 1 },
    { word: '초밥', hint: '일본식 식초 밥 위에 생선', difficulty: 1, alternates: ['스시'] },
    { word: '돈가스', hint: '돼지고기 튀김 정식', difficulty: 1 },
    { word: '제육볶음', hint: '매콤한 양념 돼지고기 볶음', difficulty: 2 },
    { word: '닭갈비', hint: '춘천이 유명한 닭 양념 요리', difficulty: 1 },
    { word: '부대찌개', hint: '햄과 소시지가 들어간 찌개', difficulty: 2 },
    { word: '순두부', hint: '말캉한 두부 찌개', difficulty: 1 },
    { word: '미역국', hint: '생일에 먹는 국', difficulty: 1 },
    { word: '갈비찜', hint: '명절 단골 메뉴 갈비 요리', difficulty: 2 },
    { word: '잡채', hint: '당면과 야채를 볶은 잔치 음식', difficulty: 1 },
    { word: '팥빙수', hint: '여름 후식, 얼음과 팥', difficulty: 2 },
    { word: '떡국', hint: '설날에 먹는 떡 요리', difficulty: 1 },
    { word: '족발', hint: '돼지 다리를 푹 삶은 음식', difficulty: 1 },
    { word: '보쌈', hint: '삶은 돼지고기를 잎채소에 싸 먹는다', difficulty: 1 },
    { word: '곱창', hint: '소·돼지 내장 구이', difficulty: 2 },
    { word: '회덮밥', hint: '회와 야채를 밥 위에 얹는다', difficulty: 2 },
    { word: '볶음밥', hint: '기름에 밥을 볶은 한 그릇 요리', difficulty: 1 },
  ],
};
