import type { CategorySeed } from '../types.js';

export const JOB: CategorySeed = {
  category: 'job',
  words: [
    { word: '의사', hint: '환자를 진료하는 사람', difficulty: 1 },
    { word: '간호사', hint: '병원에서 환자를 돌본다', difficulty: 1 },
    { word: '약사', hint: '약을 조제하는 사람', difficulty: 1 },
    { word: '변호사', hint: '법정에서 의뢰인을 변호', difficulty: 1 },
    { word: '검사', hint: '범죄를 수사하고 기소', difficulty: 1 },
    { word: '판사', hint: '재판에서 판결을 내림', difficulty: 1 },
    { word: '경찰관', hint: '치안과 범죄 단속', difficulty: 1 },
    { word: '소방관', hint: '불을 끄고 사람을 구한다', difficulty: 1 },
    { word: '군인', hint: '나라를 지키는 사람', difficulty: 1 },
    { word: '선생님', hint: '학교에서 가르치는 사람', difficulty: 1 },
    { word: '교수', hint: '대학에서 가르치는 사람', difficulty: 1 },
    { word: '연구원', hint: '실험과 연구를 하는 사람', difficulty: 1 },
    { word: '엔지니어', hint: '기술로 무언가를 만든다', difficulty: 1 },
    { word: '개발자', hint: '소프트웨어를 만든다', difficulty: 1 },
    { word: '디자이너', hint: '시각적 결과물을 만든다', difficulty: 1 },
    { word: '건축가', hint: '건물을 설계한다', difficulty: 1 },
    { word: '회계사', hint: '회계 감사를 한다', difficulty: 1 },
    { word: '세무사', hint: '세금 신고를 도와준다', difficulty: 1 },
    { word: '은행원', hint: '은행에서 일하는 사람', difficulty: 1 },
    { word: '요리사', hint: '음식을 만드는 사람', difficulty: 1 },
    { word: '제빵사', hint: '빵을 만드는 사람', difficulty: 1 },
    { word: '미용사', hint: '머리를 잘라준다', difficulty: 1 },
    { word: '화가', hint: '그림을 그리는 사람', difficulty: 1 },
    { word: '작가', hint: '글을 쓰는 사람', difficulty: 1 },
    { word: '기자', hint: '뉴스를 취재해 기사를 쓴다', difficulty: 1 },
    { word: '아나운서', hint: '방송에서 진행을 맡는다', difficulty: 1 },
    { word: '배우', hint: '영화나 드라마에 출연', difficulty: 1 },
    { word: '가수', hint: '노래를 부른다', difficulty: 1 },
    { word: '운동선수', hint: '직업으로 스포츠를 한다', difficulty: 1 },
    { word: '농부', hint: '농작물을 기른다', difficulty: 1 },
    { word: '어부', hint: '바다에서 물고기를 잡는다', difficulty: 1 },
    { word: '택시기사', hint: '승객을 태우고 운전한다', difficulty: 1 },
    { word: '조종사', hint: '비행기를 조종하는 사람', difficulty: 1 },
    { word: '승무원', hint: '비행기에서 승객을 응대', difficulty: 1 },
    { word: '공무원', hint: '국가나 지방 행정 직원', difficulty: 1 },
  ],
};
