import type { CategorySeed } from '../types.js';

// 영화/드라마 카테고리. 2~5자 제목만 (긴 제목은 줄임말 또는 키워드로).
export const MOVIE: CategorySeed = {
  category: 'movie',
  words: [
    { word: '기생충', hint: '봉준호 감독, 칸 황금종려상', difficulty: 1 },
    { word: '오징어게임', hint: '넷플릭스 글로벌 1위 한국 드라마', difficulty: 1 },
    { word: '명량', hint: '이순신 장군, 최민식 주연', difficulty: 1 },
    { word: '극한직업', hint: '치킨집 잠복 형사 코미디', difficulty: 1 },
    { word: '신과함께', hint: '저승 7개의 재판, 하정우', difficulty: 1 },
    { word: '국제시장', hint: '부산 배경 가족사 드라마', difficulty: 2 },
    { word: '베테랑', hint: '황정민 형사, 유아인 재벌', difficulty: 1 },
    { word: '암살', hint: '일제강점기 독립군, 전지현', difficulty: 1 },
    { word: '도둑들', hint: '카지노 다이아몬드 도둑단', difficulty: 1 },
    { word: '광해', hint: '이병헌 1인 2역 사극', difficulty: 1 },
    { word: '관상', hint: '얼굴로 운명을 본다는 송강호', difficulty: 1 },
    { word: '왕의남자', hint: '광대와 임금 사극, 이준기', difficulty: 1 },
    { word: '실미도', hint: '북파 공작원 실화 영화', difficulty: 2 },
    { word: '괴물', hint: '한강에 나타난 그것, 송강호', difficulty: 1 },
    { word: '추격자', hint: '나홍진 데뷔작 스릴러', difficulty: 1 },
    { word: '아저씨', hint: '원빈 주연 액션', difficulty: 1 },
    { word: '부산행', hint: '좀비가 점령한 KTX', difficulty: 1 },
    { word: '곡성', hint: '나홍진 미스터리, 황정민', difficulty: 1 },
    { word: '아가씨', hint: '박찬욱 감독, 김민희 김태리', difficulty: 1 },
    { word: '미나리', hint: '한국계 미국 가족, 윤여정 오스카', difficulty: 1 },
    { word: '헤어질결심', hint: '박찬욱 감독, 탕웨이 박해일', difficulty: 2 },
    { word: '범죄도시', hint: '마동석 형사 액션 시리즈', difficulty: 1 },
    { word: '태극기', hint: "6.25 형제 드라마 '~휘날리며'", difficulty: 2 },
    { word: '겨울왕국', hint: '엘사와 안나의 디즈니 애니', difficulty: 1 },
    { word: '도깨비', hint: '공유와 김고은의 판타지 드라마', difficulty: 1 },
    { word: '우영우', hint: '자폐 변호사 드라마 주인공 박은빈', difficulty: 2 },
    { word: '시그널', hint: '과거와 무전 통화 김혜수', difficulty: 1 },
    { word: '비밀의숲', hint: '검사 조승우 형사 배두나', difficulty: 2 },
    { word: '응답하라', hint: "추억의 시리즈 '~1988'", difficulty: 1 },
    {
      word: '슬의생',
      hint: '병원 99즈 의사들 드라마 줄임말',
      difficulty: 2,
      alternates: ['슬기로운의사생활'],
    },
    { word: '더글로리', hint: '송혜교 학폭 복수극', difficulty: 1 },
    {
      word: '재벌집막내',
      hint: '회귀물, 송중기 주연',
      difficulty: 2,
      alternates: ['재벌집막내아들'],
    },
    {
      word: '나의해방',
      hint: '경기도민 3남매 드라마, IU의 노래',
      difficulty: 2,
      alternates: ['나의해방일지'],
    },
  ],
};
