import type { CategorySeed } from '../types.js';

export const OBJECT: CategorySeed = {
  category: 'object',
  words: [
    { word: '책상', hint: '공부할 때 앞에 두는 가구', difficulty: 1 },
    { word: '의자', hint: '앉기 위한 가구', difficulty: 1 },
    { word: '침대', hint: '잠을 자는 가구', difficulty: 1 },
    { word: '책장', hint: '책을 꽂아두는 가구', difficulty: 1 },
    { word: '냉장고', hint: '음식을 차게 보관하는 가전', difficulty: 1 },
    { word: '세탁기', hint: '옷을 빨아주는 가전', difficulty: 1 },
    { word: '에어컨', hint: '여름에 시원하게 해주는 가전', difficulty: 1 },
    { word: '선풍기', hint: '바람을 만들어주는 가전', difficulty: 1 },
    { word: '텔레비전', hint: '큰 화면으로 방송을 본다', difficulty: 1, alternates: ['티비'] },
    { word: '전자레인지', hint: '음식을 빠르게 데우는 가전', difficulty: 2 },
    { word: '컴퓨터', hint: '인터넷도 하고 일도 하는 기계', difficulty: 1 },
    { word: '노트북', hint: '들고 다니는 컴퓨터', difficulty: 1 },
    { word: '키보드', hint: '컴퓨터 글자 입력 장치', difficulty: 1 },
    { word: '마우스', hint: '클릭하는 입력 장치', difficulty: 1 },
    { word: '휴대폰', hint: '들고 다니는 전화', difficulty: 1, alternates: ['핸드폰'] },
    { word: '이어폰', hint: '귀에 꽂는 음향기기', difficulty: 1 },
    { word: '카메라', hint: '사진을 찍는 기계', difficulty: 1 },
    { word: '시계', hint: '시간을 알려주는 도구', difficulty: 1 },
    { word: '거울', hint: '내 모습을 비추는 물건', difficulty: 1 },
    { word: '우산', hint: '비 올 때 펴는 도구', difficulty: 1 },
    { word: '안경', hint: '눈에 쓰는 시력 보조 도구', difficulty: 1 },
    { word: '연필', hint: '나무로 된 필기도구', difficulty: 1 },
    { word: '지우개', hint: '연필 자국을 지우는 물건', difficulty: 1 },
    { word: '가위', hint: '종이를 자르는 도구', difficulty: 1 },
    { word: '딱풀', hint: '종이를 붙이는 막대형 풀', difficulty: 1 },
    { word: '공책', hint: '글씨를 쓰는 종이 묶음', difficulty: 1 },
    { word: '책가방', hint: '학교 갈 때 메는 가방', difficulty: 1 },
    { word: '운동화', hint: '운동할 때 신는 신발', difficulty: 1 },
    { word: '구두', hint: '정장에 어울리는 신발', difficulty: 1 },
    { word: '양말', hint: '신발 안에 신는 천', difficulty: 1 },
    { word: '모자', hint: '머리에 쓰는 물건', difficulty: 1 },
    { word: '장갑', hint: '겨울에 손에 끼는 물건', difficulty: 1 },
    { word: '목도리', hint: '겨울에 목에 두르는 천', difficulty: 1 },
    { word: '베개', hint: '잘 때 머리를 받치는 물건', difficulty: 1 },
    { word: '이불', hint: '잘 때 덮는 천', difficulty: 1 },
    { word: '수건', hint: '몸을 닦는 천', difficulty: 1 },
    { word: '칫솔', hint: '이를 닦는 도구', difficulty: 1 },
    { word: '치약', hint: '칫솔에 짜는 흰 액체', difficulty: 1 },
    { word: '비누', hint: '손을 씻을 때 사용', difficulty: 1 },
    { word: '신문', hint: '뉴스를 종이로 보는 매체', difficulty: 1 },
  ],
};
