import type { CategorySeed } from '../types.js';

export const PLACE: CategorySeed = {
  category: 'place',
  words: [
    { word: '서울', hint: '대한민국의 수도', difficulty: 1 },
    { word: '부산', hint: '해운대로 유명한 항구 도시', difficulty: 1 },
    { word: '제주도', hint: '한국 최대의 섬', difficulty: 1 },
    { word: '대구', hint: '경상북도의 큰 도시', difficulty: 1 },
    { word: '인천', hint: '국제공항이 있는 항구 도시', difficulty: 1 },
    { word: '광주', hint: '전라남도 중심 도시', difficulty: 1 },
    { word: '대전', hint: '한국 중부 과학 도시', difficulty: 1 },
    { word: '울산', hint: '현대 자동차의 본고장', difficulty: 1 },
    { word: '경주', hint: '신라의 천년 수도', difficulty: 1 },
    { word: '전주', hint: '한옥마을과 비빔밥', difficulty: 1 },
    { word: '강릉', hint: '동해 바다와 커피 거리', difficulty: 1 },
    { word: '속초', hint: '설악산 입구 항구 도시', difficulty: 1 },
    { word: '여수', hint: '밤바다가 유명한 항구', difficulty: 1 },
    { word: '도쿄', hint: '일본의 수도', difficulty: 1 },
    { word: '오사카', hint: '일본 제2의 도시, 다코야키', difficulty: 1 },
    { word: '교토', hint: '일본의 옛 수도', difficulty: 1 },
    { word: '베이징', hint: '중국의 수도', difficulty: 1 },
    { word: '상하이', hint: '중국 최대 경제 도시', difficulty: 1 },
    { word: '파리', hint: '에펠탑이 있는 프랑스 수도', difficulty: 1 },
    { word: '런던', hint: '빅벤이 있는 영국 수도', difficulty: 1 },
    { word: '뉴욕', hint: '자유의 여신상, 미국 동부', difficulty: 1 },
    { word: '도서관', hint: '책을 빌릴 수 있는 곳', difficulty: 1 },
    { word: '학교', hint: '학생들이 공부하는 곳', difficulty: 1 },
    { word: '병원', hint: '아플 때 가는 곳', difficulty: 1 },
    { word: '공항', hint: '비행기를 타는 곳', difficulty: 1 },
    { word: '시장', hint: '물건을 사고파는 곳', difficulty: 1 },
    { word: '백화점', hint: '여러 매장이 있는 큰 쇼핑몰', difficulty: 1 },
    { word: '편의점', hint: '24시간 영업하는 작은 가게', difficulty: 1 },
    { word: '카페', hint: '커피 마시는 곳', difficulty: 1 },
    { word: '식당', hint: '밥 먹으러 가는 곳', difficulty: 1 },
    { word: '영화관', hint: '큰 화면으로 영화를 본다', difficulty: 1 },
    { word: '놀이공원', hint: '롤러코스터가 있는 곳', difficulty: 1 },
    { word: '동물원', hint: '여러 동물을 구경하는 곳', difficulty: 1 },
    { word: '수족관', hint: '바다 생물을 구경하는 곳', difficulty: 1 },
    { word: '박물관', hint: '역사 유물을 보는 곳', difficulty: 1 },
    { word: '미술관', hint: '그림과 작품을 본다', difficulty: 1 },
    { word: '경복궁', hint: '서울 대표 조선 왕궁', difficulty: 1 },
    { word: '한라산', hint: '제주도에 있는 화산', difficulty: 1 },
    { word: '백두산', hint: '한반도 최고봉', difficulty: 1 },
    { word: '설악산', hint: '강원도의 명산', difficulty: 1 },
  ],
};
