import type { CategorySeed } from '../types.js';

export const SPORTS: CategorySeed = {
  category: 'sports',
  words: [
    { word: '축구', hint: '11명이 공을 발로 차는 운동', difficulty: 1 },
    { word: '야구', hint: '방망이로 공을 치는 운동', difficulty: 1 },
    { word: '농구', hint: '바스켓에 공을 넣는다', difficulty: 1 },
    { word: '배구', hint: '네트를 사이에 두고 손으로 공을', difficulty: 1 },
    { word: '탁구', hint: '작은 공과 라켓의 실내 스포츠', difficulty: 1 },
    { word: '테니스', hint: '큰 라켓으로 노란 공을', difficulty: 1 },
    { word: '배드민턴', hint: '셔틀콕을 라켓으로', difficulty: 1 },
    { word: '골프', hint: '작은 공을 홀에 넣는 스포츠', difficulty: 1 },
    { word: '수영', hint: '물에서 하는 운동', difficulty: 1 },
    { word: '스키', hint: '눈 위를 빠르게 미끄러지는 운동', difficulty: 1 },
    { word: '스노보드', hint: '한 보드 위에서 눈을 탄다', difficulty: 1 },
    { word: '스케이트', hint: '얼음 위를 빠르게', difficulty: 1 },
    {
      word: '피겨',
      hint: '얼음판 위 점프와 회전 빙상 종목',
      difficulty: 2,
      alternates: ['피겨스케이팅'],
    },
    { word: '복싱', hint: '두 사람이 글러브로', difficulty: 1 },
    { word: '태권도', hint: '한국의 대표 무술', difficulty: 1 },
    { word: '유도', hint: '메치기와 굳히기의 격투기', difficulty: 1 },
    { word: '검도', hint: '죽도로 겨루는 무술', difficulty: 1 },
    { word: '양궁', hint: '활을 쏘는 한국 강세 종목', difficulty: 1 },
    { word: '사격', hint: '총으로 표적을 맞추는 종목', difficulty: 1 },
    { word: '체조', hint: '평균대, 마루, 도마 종목', difficulty: 1 },
    { word: '육상', hint: '달리기, 멀리뛰기, 던지기', difficulty: 1 },
    { word: '마라톤', hint: '42.195km 장거리 달리기', difficulty: 1 },
    { word: '하키', hint: '스틱으로 퍽이나 공을', difficulty: 1 },
    { word: '럭비', hint: '타원형 공의 격렬한 스포츠', difficulty: 1 },
    { word: '미식축구', hint: '미국식 풋볼', difficulty: 1 },
    { word: '볼링', hint: '핀을 굴려 쓰러뜨린다', difficulty: 1 },
    { word: '당구', hint: '큐로 공을 친다', difficulty: 1 },
    { word: '월드컵', hint: '4년에 한 번 축구 세계대회', difficulty: 1 },
    { word: '올림픽', hint: '4년마다 열리는 국제 종합대회', difficulty: 1 },
    { word: '아시안게임', hint: '아시아 대륙 종합 대회', difficulty: 1 },
    { word: '메달', hint: '시상대에서 받는 금속 상', difficulty: 1 },
    { word: '코치', hint: '선수를 가르치는 사람', difficulty: 1 },
    { word: '심판', hint: '경기를 판정하는 사람', difficulty: 1 },
  ],
};
